package world.verifi.auto_connect

enum class AutoConnectAction(private val methodName: String) {
  INITIALIZE(INITIALIZE_METHOD),
  GET_GEOFENCES(GET_GEOFENCES_METHOD),
  REMOVE_ALL_GEOFENCES(REMOVE_ALL_GEOFENCES_METHOD),
  GET_PINNED_GEOFENCES(GET_PINNED_GEOFENCES_METHOD),
  ADD_GEOFENCE_WITH_AP(ADD_GEOFENCE_WITH_AP_METHOD),
  REMOVE_GEOFENCE_WITH_AP(REMOVE_GEOFENCE_WITH_AP_METHOD),
  CONNECT_TO_AP(CONNECT_TO_AP_METHOD),
  ADD_PIN_AP(ADD_PIN_AP_METHOD),
  REMOVE_PIN_AP(REMOVE_PIN_AP_METHOD),
  IS_AP_PINNED(IS_AP_PINNED_METHOD),
  BACKGROUND_CHANNEL_INITIALIZED(BACKGROUND_CHANNEL_INITIALIZED_METHOD),
  LOCATION_EVENT_COMPLETED(LOCATION_EVENT_COMPLETED_METHOD),
  ACCESS_POINT_EVENT_COMPLETED(ACCESS_POINT_EVENT_COMPLETED_METHOD),
  UNDEFINED_ACTION(NO_SUCH_METHOD);

  companion object {
    fun fromMethod(method: String): AutoConnectAction {
      for (action in values()) {
        if (action.methodName == method) {
          return action
        }
      }
      return UNDEFINED_ACTION
    }

  }
}
